import type { Chapter } from '../types'
import { prologue } from './prologue'
import { gfs } from './gfs'
import { mapreduce } from './mapreduce'
import { bigtable } from './bigtable'
import { rum } from './rum'
import { chubby } from './chubby'
import { dynamo } from './dynamo'
import { cap } from './cap'
import { cassandra } from './cassandra'
import { lamport } from './lamport'
import { consensus } from './consensus'
import { zookeeper } from './zookeeper'
import { percolator } from './percolator'
import { spanner } from './spanner'
import { memcache } from './memcache'
import { kafka } from './kafka'
import { aurora } from './aurora'
import { columnar } from './columnar'
import { snowflake } from './snowflake'
import { dynamodb } from './dynamodb'
import { season1 } from './season-1'
import { spark } from './spark'
import { naiad } from './naiad'
import { structuredStreaming } from './structured-streaming'
import { millwheel } from './millwheel'
import { threeTimes } from './three-times'
import { dataflow } from './dataflow'
import { flinkSnapshots } from './flink-snapshots'
import { differential } from './differential'
import { noria } from './noria'
import { dbsp } from './dbsp'
import { crdt } from './crdt'
import { localFirst } from './local-first'
import { delta } from './delta'
import { unbundling } from './unbundling'
import { season2 } from './season-2'
import { flp } from './flp'

/** Chapters that exist, in reading order — interludes included, since they are
 *  pages a reader walks through. The season's full map, including everything
 *  unwritten, lives in book.ts (TOC); this is only what is live. */
export const CHAPTERS: Chapter[] = [prologue, gfs, mapreduce, bigtable, rum, chubby, dynamo, cap, cassandra, lamport, consensus, zookeeper, percolator, spanner, memcache, kafka, aurora, columnar, snowflake, dynamodb, season1, spark, naiad, structuredStreaming, millwheel, threeTimes, dataflow, flinkSnapshots, differential, noria, dbsp, crdt, localFirst, delta, unbundling, season2, flp]

export const CHAPTER_BY_SLUG: Record<string, Chapter> = Object.fromEntries(CHAPTERS.map((c) => [c.slug, c]))
